import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            <SignInButton>
              <button className="bg-white text-gray-500 hover:bg-gray-100 py-2 px-4 rounded">
                Sign In
              </button>
            </SignInButton>
          </SignedOut>
          <SignedIn>
            <UserButton>
              <button className="bg-white text-gray-500 hover:bg-gray-100 py-2 px-4 rounded">
                Sign Out
              </button>
            </UserButton>
          </SignedIn>
          {children}

          <h1 className="text-center">NextJS 14</h1>
        </body>
      </html>
    </ClerkProvider>
  );
}
